ruby_version: 3.4.1

ignore:
  - 'bin/**/*'
  - 'vendor/**/*'
  - 'db/schema.rb'

plugins:
  - standard-custom
  - standard-performance

standard_custom:
  rules:
    lambda_call_style: 
      enabled: false
      style: "call"
    
    lambda_syntax:
      enabled: false
      style: "line_count_dependent"
    
    copyright_notice:
      enabled: false
