# Released under the MIT License.
# Copyright, 2023, by Aristóteles Coutinho.

# [Choice] Ruby version: 3, 3.0, 2, 2.7, 2.6
ARG VARIANT="3"
FROM mcr.microsoft.com/devcontainers/ruby:${VARIANT}

RUN apt-get update