#!/usr/bin/env ruby

# Released under the MIT License.
# Copyright, 2023-2025, by Aristóteles Coutinho.

# Require the main file
#
# @private `Since v0.1`
#
require "lennarb"

# Show the version
#
puts Lennarb::VERSION
